uint8 output
uint8 OUTPUT_BOTH = 0
uint8 OUTPUT_YAW = 1
uint8 OUTPUT_YAWRATE = 2

uint8 mode
uint8 MODE_STOP = 0
uint8 MODE_ONE_TIME = 1
uint8 MODE_CONTINUE_20MS = 2
uint8 MODE_CONTINUE_50MS = 3
uint8 MODE_CONTINUE_100MS = 4
uint8 MODE_CONTINUE_200MS = 5
uint8 MODE_CONTINUE_250MS = 6
uint8 MODE_CONTINUE_500MS = 7
uint8 MODE_CONTINUE_1000MS = 8

---

int8 result
int8 RESULT_FAIL = -1
int8 RESULT_DONE = 0